/**
 * Turns an artist SVG export into a Motif module.
 *
 *   pnpm motif <input.svg> [name]
 *
 * Concepts exports carry the reference photo the drawing was traced over as a base64
 * <image> in <defs> — that is almost all of the file size and none of the line art.
 * It is stripped first, then svgo reduces the path data, then the `d` attributes are
 * emitted as a plain string array.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'

import { optimize } from 'svgo'

import { flatten, rdp, toPathData } from './simplify-path.mjs'

const [input, nameArg, epsArg] = process.argv.slice(2)
if (!input) {
  console.error('usage: pnpm motif <input.svg> [name] [epsilon]')
  process.exit(1)
}
/** In viewBox units. The ammonite's box is ~850 tall, so 0.4 is far under a pixel on screen. */
const EPSILON = Number(epsArg ?? 0.4)

const name = nameArg ?? path.basename(input).replace(/\.svg$/i, '').replace(/[^a-z0-9]+/gi, '-').toLowerCase()
const raw = readFileSync(input, 'utf8')
const before = Buffer.byteLength(raw)

// Drop embedded rasters (and any <defs> left empty by their removal).
const stripped = raw
  .replace(/<image\b[\s\S]*?(?:\/>|<\/image>)/gi, '')
  .replace(/<defs>\s*<\/defs>/gi, '')

const { data } = optimize(stripped, {
  multipass: true,
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          // viewBox is how the motif scales — never let it be removed.
          removeViewBox: false,
          // Keep paths separate: the pen renderer strokes them one at a time.
          mergePaths: false,
          convertPathData: { floatPrecision: 2, transformPrecision: 3 },
        },
      },
    },
    'removeDimensions',
  ],
})

const viewBox = data.match(/viewBox="([^"]+)"/)?.[1]
if (!viewBox) throw new Error('no viewBox found after optimisation')

const rawPaths = [...data.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
if (rawPaths.length === 0) throw new Error('no <path> elements found')

// Flatten curves to polylines, then drop the redundant stylus samples.
let rawPoints = 0
let keptPoints = 0
const paths = []
for (const d of rawPaths) {
  for (const sub of flatten(d)) {
    rawPoints += sub.length
    const simplified = rdp(sub, EPSILON)
    if (simplified.length < 2) continue
    keptPoints += simplified.length
    paths.push(toPathData(simplified))
  }
}
if (paths.length === 0) throw new Error('everything simplified away — lower the epsilon')

// Concepts writes a stroke-width per path; they are uniform in practice, so take the first.
const strokeWidth = Number(data.match(/stroke-width="([\d.]+)"/)?.[1] ?? 1.5)

const outDir = path.resolve('src/motifs/generated')
mkdirSync(outDir, { recursive: true })
const outFile = path.join(outDir, `${name}.ts`)

const body = `import type { Motif } from '../types'

/** Generated by \`pnpm motif\` from ${path.basename(input)}. Do not edit by hand. */
export const ${toIdent(name)}: Motif = {
  name: ${JSON.stringify(name)},
  viewBox: ${JSON.stringify(viewBox)},
  strokeWidth: ${strokeWidth},
  paths: ${JSON.stringify(paths, null, 2).replace(/\n/g, '\n  ')},
}
`
writeFileSync(outFile, body)

const after = Buffer.byteLength(body)
console.log(
  `${name}: ${rawPaths.length} source paths -> ${paths.length} polylines, strokeWidth ${strokeWidth}\n` +
    `  points ${rawPoints} -> ${keptPoints} (${((1 - keptPoints / rawPoints) * 100).toFixed(1)}% dropped, epsilon ${EPSILON})\n` +
    `  ${(before / 1024 / 1024).toFixed(2)} MB in -> ${(after / 1024).toFixed(1)} KB out  (${outFile})`,
)

function toIdent(s) {
  return s.replace(/[^a-z0-9]+(.)?/gi, (_, c) => (c ? c.toUpperCase() : ''))
}
